apps/main/urls.py
from django.urls import path

from . import views


app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
    path('public-servers/', views.public_servers, name="public-servers"),
    path('manage/', views.manage, name='manage'),
    path('server/add/', views.add, name="add"),
    path('server/<int:id>/edit/', views.edit, name="edit"),
    path('server/<int:id>/properties/', views.properties, name="properties"),
    path('server/<int:id>/permissions/', views.permissions, name="permissions"),
    path('server/<int:id>/share/', views.share, name="share"),
    path('server/<int:id>/delete/', views.delete, name="delete"),
    path('server/<int:id>/start/', views.start, name="start"),
    path('server/<int:id>/stop/', views.stop, name="stop"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include("social_django.urls", namespace="social")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

apps/main/forms.py
from django import forms
from .models import ServerShare, Server, ServerProperties

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row, Submit, HTML
from crispy_forms.bootstrap import FormActions

class ServerShareForm(forms.ModelForm):
    helper = FormHelper()
    helper.layout = Layout(
        Row(
            Column("user"),
            Column("level"),
        ),
        FormActions(
            Submit('save', 'Enregistrer'),
            HTML('<input type="reset" name="cancel" value="Annuler" class="btn btn-secondary">'),
        )
    )

    class Meta:
        model = ServerShare
        fields = [
            'user',
            'level',
        ]


class ServerForm(forms.ModelForm):
    helper = FormHelper()
    helper.layout = Layout(
        Row(
            Column(
                "name",
                "public",
            ),
            Column("version"),
        ),
        "description",
        "image",
        FormActions(
            Submit('save', 'Enregistrer'),
            HTML('<input type="reset" name="cancel" value="Annuler" class="btn btn-secondary">'),
        )
    )

    class Meta:
        model = Server
        fields = [
            "name",
            "version",
            "description",
            "image",
            "public",
        ]
        widgets = {
            'description': forms.Textarea(attrs={'rows': 6})
        }


class PropertiesForm(forms.ModelForm):
    helper = FormHelper()
    helper.layout = Layout(
        Row(
            Column(
                "gamemode",
                "difficulty",
                "view_distance",
            ),
            Column(
                "max_players",
                "level_name",
                "level_seed",
            ),
        ),
        Row(
            Column(
                "force_gamemode",
            ),
        ),
        Row(
            Column(
                "motd",
            ),
            Column(
                "spawn_protection",
                "hardcore",
                "pvp",
                "generate_structures",
            ),
        ),
        Row(
            Column(
                "spawn_npcs",
                "spawn_animals",
                "spawn_monsters",
            ),
            Column(
                "enforce_whitelist",
                "online_mode",
                "enable_command_block",
            ),
        ),
        FormActions(
            Submit('save', 'Enregistrer'),
            HTML('<input type="reset" name="cancel" value="Annuler" class="btn btn-secondary">'),
        )
    )

    class Meta:
        model = ServerProperties
        fields = [
            "max_players",
            "view_distance",
            "level_seed",
            "gamemode",
            "force_gamemode",
            "difficulty",
            "level_name",
            "motd",
            "spawn_protection",
            "hardcore",
            "pvp",
            "generate_structures",
            "spawn_npcs",
            "spawn_animals",
            "spawn_monsters",
            "enforce_whitelist",
            "online_mode",
            "enable_command_block",
        ]
        widgets = {
            'motd': forms.Textarea(attrs={'rows': 6})
        }


class PermissionForm(forms.Form):

    nickname = forms.CharField(
        max_length=128,
        label="Nom du joueur",
    )

    helper = FormHelper()
    helper.layout = Layout(
        'nickname',
        FormActions(
            Submit('save', 'Enregistrer'),
            HTML('<input type="reset" name="cancel" value="Annuler" class="btn btn-secondary">'),
        ),
    )

apps/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.core.exceptions import PermissionDenied

from .forms import ServerShareForm, ServerForm, PropertiesForm, PermissionForm
from .models import Server, ServerProperties


# Decorators
def owner_expected(function):
    def decorator(*args, **kwargs):
        server = get_object_or_404(Server, pk=kwargs['id'])
        if server.owner != args[0].user:
            raise PermissionDenied
        return function(*args, **kwargs)
    return decorator


# Views
def index(request):
    context = {}
    return render(request, 'main/index.html', context)


def public_servers(request):
    context = {
        'servers': Server.objects.filter(public=True)
    }
    return render(request, 'main/list.html', context)


@login_required
def manage(request):
    servers = Server.objects.filter(owner=request.user)
    context = {
        'servers': servers,
        'delete_success': 'delete' in request.GET,
        'start_success': 'start' in request.GET,
        'stop_success': 'stop' in request.GET,
    }
    return render(request, 'main/manage.html', context)


@login_required
def add(request):
    form = ServerForm(
        data=request.POST or None,
        files=request.FILES or None,
        label_suffix='',
    )

    if request.method == 'POST' and form.is_valid:
        new_server = form.save()
        new_server.owner = request.user
        new_server.save()
        return HttpResponseRedirect(reverse('main:edit', args=[new_server.pk]) + "?create=1")

    context = {
        'form': form,
    }
    return render(request, 'main/add.html', context)


@login_required
@owner_expected
def edit(request, id):
    server = get_object_or_404(Server, pk=id)
    form = ServerForm(
        data=request.POST or None,
        files=request.FILES or None,
        label_suffix='',
        instance=server,
    )
    success = None
    if request.method == 'POST':
        if form.has_changed() and form.is_valid():
            form.save()
            success = True

    context = {
        'server': server,
        'form': form,
        'success': success,
        'create_success': 'create' in request.GET,
    }
    return render(request, 'main/settings/edit.html', context)


@login_required
@owner_expected
def properties(request, id):
    server = get_object_or_404(Server, pk=id)
    properties = get_object_or_404(ServerProperties, server=server)
    form = PropertiesForm(
        data=request.POST or None,
        label_suffix='',
        instance=properties,
    )
    success = None
    if request.method == 'POST':
        if form.has_changed() and form.is_valid():
            form.save()
            success = True

    context = {
        'server': server,
        'properties': properties,
        'form': form,
        'success': success,
    }
    return render(request, 'main/settings/properties.html', context)


@login_required
@owner_expected
def permissions(request, id):
    server = get_object_or_404(Server, pk=id)
    form = PermissionForm(
        data=request.POST or None,
    )
    success = None
    if request.method == 'POST':
        if form.is_valid():
            server.op(form.cleaned_data['nickname'])
            success = True
    ops = server.get_ops()

    context = {
        'server': server,
        'form': form,
        'success': success,
        'ops': ops,
    }
    return render(request, 'main/settings/permissions.html', context)


@login_required
@owner_expected
def share(request, id):
    server = get_object_or_404(Server, pk=id)
    form = ServerShareForm(
        data=request.POST or None,
    )
    success = None
    if request.method == 'POST':
        if form.is_valid():
            if form.cleaned_data['user'].pk != request.user.pk:
                share = form.save()
                server.shares.add(share)
                server.save()
                success = True
                form = ServerShareForm()
            else:
                success = False
    context = {
        'server': server,
        'form': form,
        'success': success
    }
    return render(request, 'main/settings/share.html', context)


@login_required
@owner_expected
def delete(request, id):
    server = get_object_or_404(Server, pk=id)
    server.delete()
    return HttpResponseRedirect(reverse('main:manage') + "?delete=1")


@login_required
@owner_expected
def start(request, id):
    server = get_object_or_404(Server, pk=id)
    if server.owner == request.user:
        server.start()
    return HttpResponseRedirect(reverse('main:manage') + "?start=1")


@login_required
@owner_expected
def stop(request, id):
    server = get_object_or_404(Server, pk=id)
    if server.owner == request.user:
        server.stop()
    return HttpResponseRedirect(reverse('main:manage') + "?stop=1")

apps/main/templates/main/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block title %}Ajouter un serveur{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="pb-3">
        <a href="{% url 'main:manage' %}" class="btn btn-primary">← Retour</a>
    </div>
    <div class="mb-4">
        {% crispy form %}
    </div>
{% endblock content %}

apps/main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Serveurs Minecraft{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Bienvenue sur le gestionnaire de serveurs Minecraft</h1>
        <p class="lead">
            Vous pouvez créer des serveurs Minecraft lorsque vous en avez besoin juste ici !
        </p>
        <hr class="my-4">
        <p>
            Il n'y a qu'une seule règle : éteindre le serveur lorsque vous n'en avez plus besoin.
        </p>
        <a class="btn btn-primary btn-lg" href="{% url 'main:public-servers' %}" role="button">Parcourir les serveurs publics</a>
    </div>
{% endblock content %}

apps/main/templates/main/manage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Gestion des serveurs{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="text-right pb-3">
        <a href="{% url 'main:add' %}" class="btn btn-primary">+ Ajouter un serveur</a>
    </div>
    {% if delete_success %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        Le serveur a bien été supprimé.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% if start_success %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        Le serveur va bientôt démarrer.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% if stop_success %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        Le serveur va bientôt s'éteindre.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {% if servers %}
            {% for server in servers %}
                {% include 'main/components/server_card.html' %}
            {% endfor %}
        {% else %}
            <p>Vous ne possédez aucun serveur.</p>
        {% endif %}
    </div>
{% endblock content %}