apps/core/urls.py
from django.urls import include, path

from core import views

app_name = "core"
urlpatterns = [
    path('', views.DefaultView.as_view(), name='index'),
    path('public-servers/', views.ServerListView.as_view(), name="public-servers"),
    path('manage/', views.ServerManageView.as_view(), name='manage'),
    path('server/add/', views.ServerCreateView.as_view(), name="add"),
    path('server/<int:id>/', include([
        path('share/<int:share_id>/', include([
            path('edit/', views.ServerShareEditView.as_view(), name="share-edit"),
            path('delete/', views.ServerShareDeleteView.as_view(), name="share-delete"),
        ])),
        path('edit/', views.ServerEditView.as_view(), name="edit"),
        path('properties/', views.ServerPropertiesView.as_view(), name="properties"),
        path('permissions/', views.ServerPermissionView.as_view(), name="permissions"),
        path('shares/', views.ServerSharesView.as_view(), name="shares"),
        path('delete/', views.ServerDeleteView.as_view(), name="delete"),
        path('start/', views.ServerStartView.as_view(), name="start"),
        path('stop/', views.ServerStopView.as_view(), name="stop"),
    ])),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include("social_django.urls", namespace="social")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

apps/core/models/functions.py
from os.path import join

from django.conf import settings


def image_upload_to(instance, filename: str):
    """Give the file path for uploading server icon."""
    filepath = join(
        'server',
        'server-icon_%.3d.png',
    )
    return filepath % instance.pk

apps/core/forms/PermissionForm.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Column, Layout, Row, Submit
from django import forms


class PermissionForm(forms.Form):
    nickname = forms.CharField(
        max_length=128,
        label="Nom du joueur",
    )
    helper = FormHelper()
    helper.layout = Layout(
        'nickname',
        FormActions(
            Submit('save', 'Enregistrer'),
            HTML('<input type="reset" name="cancel" value="Annuler" class="btn btn-secondary">'),
        ),
    )

apps/core/views/DefaultView.py
from django.views.generic import TemplateView


class DefaultView(TemplateView):
    """This view render the default view."""

    template_name = "core/index.html"

apps/core/views/ServerCreateView.py
from core.exceptions import NotRunningError
from core.forms import ServerForm
from core.models import Server
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View


@method_decorator(login_required, name='dispatch')
class ServerCreateView(View):
    """This is the server create view."""

    def get(self, request):
        form = ServerForm(data=request.POST or None)
        context = {
            'form': form,
        }
        return render(request, 'core/add.html', context)

    def post(self, request):
        form = ServerForm(
            data=request.POST,
            files=request.FILES,
        )
        if form.is_valid():
            new_server = form.save()
            new_server.owner = request.user
            new_server.save()
            messages.add_message(
                request=request,
                level=messages.INFO,
                message='Le serveur a bien été créé.',
            )
            return HttpResponseRedirect(reverse('core:edit', args=[new_server.pk]))
        else:
            messages.add_message(
                request=request,
                level=messages.ERROR,
                message='Le formulaire est incorrect.',
            )
        return self.get(request)

apps/core/views/ServerDeleteView.py
from core.models import Server
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, get_object_or_404, reverse
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization(), name='dispatch')
class ServerDeleteView(View):
    """This is the delete view."""

    def get(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        server.delete()
        messages.add_message(
            request=request,
            level=messages.INFO,
            message='Le serveur vient d\'être supprimé.',
        )
        return HttpResponseRedirect(reverse('core:manage'))

apps/core/views/ServerEditView.py
from core.exceptions import NotRunningError
from core.forms import ServerForm
from core.models import Server
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization, owner_expected


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('manage'), name='dispatch')
class ServerEditView(View):
    """This is the server edit view."""

    def get(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        form = ServerForm(
            data=request.POST or None,
            instance=server,
        )
        context = {
            'server': server,
            'form': form,
        }
        return render(request, 'core/settings/edit.html', context)

    def post(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        form = ServerForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=server,
        )
        if form.has_changed() and form.is_valid():
            form.save()
            messages.add_message(
                request=request,
                level=messages.INFO,
                message='Les paramètres du serveur ont bien été enregistrés.',
            )
        return self.get(request, id)

apps/core/views/ServerListView.py
from core.models import Server
from django.views.generic import TemplateView


class ServerListView(TemplateView):
    """This is the view for listing public servers."""

    template_name = 'core/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['servers'] = Server.objects.filter(public=True)
        return context

apps/core/views/ServerManageView.py
from core.models import Server, ServerShare
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView


@method_decorator(login_required, name='dispatch')
class ServerManageView(TemplateView):
    """This view render the user server list."""

    template_name = 'core/manage.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['servers'] = Server.objects.filter(owner=self.request.user)
        shares = ServerShare.objects.filter(user=self.request.user)
        context['shared_servers'] = [ share.server for share in shares ]
        return context

apps/core/views/ServerPermissionView.py
from core.exceptions import NotRunningError
from core.forms import PermissionForm
from core.models import Server
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('administrators'), name='dispatch')

class ServerPermissionView(View):
    """This is the permission view."""

    def get(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        form = PermissionForm(
            data=request.POST or None,
        )
        context = {
            'server': server,
            'form': form,
            'ops': server.get_ops(),
        }
        return render(request, 'core/settings/permissions.html', context)

    def post(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        form = PermissionForm(data=request.POST or None)
        if form.is_valid():
            try:
                server.op(form.cleaned_data['nickname'])
                name = form.cleaned_data['nickname']
                message = '%s a bien été ajouté à la liste des administrateurs' % name
                messages.add_message(
                    request=request,
                    level=messages.INFO,
                    message=message,
                )
                messages.add_message(
                    request=request,
                    level=messages.WARNING,
                    message='L\'information va être traitée sous peu.' +
                    ' Vous devrez peut-être recharcher cette page pour voir apparaître un changement.'
                )
            except NotRunningError:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message='Le serveur est à l\'arrêt. Impossible de traiter la demande',
                )
        return self.get(request, id)
        

apps/core/views/ServerPropertiesView.py
from core.exceptions import NotRunningError
from core.forms import PropertiesForm
from core.models import Server
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('properties'), name='dispatch')
class ServerPropertiesView(View):
    """This is the properties view."""

    def get(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        properties = server.get_properties()
        form = PropertiesForm(
            data=request.POST or properties,
            label_suffix='',
        )
        context = {
            'server': server,
            'form': form,
            'properties_created': properties is not None,
        }
        return render(request, 'core/settings/properties.html', context)

    def post(self, request, id: int):
        server = get_object_or_404(Server, pk=id)
        form = PropertiesForm(data=request.POST)
        if form.is_valid():
            server.set_properties(form.cleaned_data)
            messages.add_message(
                request=request,
                level=messages.INFO,
                message='Les propriétés du serveur on bien été enregistrées.',
            )
            if server.get_status() == 1:
                messages.add_message(
                    request=request,
                    level=messages.WARNING,
                    message='Vous devez redémarrer le serveur pour les prendre en compte.',
                )
            return HttpResponseRedirect(reverse('core:properties', args=[id]))
        else:
            messages.add_message(
                request=request,
                level=messages.ERROR,
                message='Le formulaire est incorrect.',
            )
            return self.get(request, id)

apps/core/views/ServerShareDeleteView.py
from core.models import ServerShare
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect, get_object_or_404, reverse
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('administrators'), name='dispatch')
class ServerShareDeleteView(View):
    """This is the server share delete view."""

    def get(self, request, id: int, share_id: int):
        share = get_object_or_404(ServerShare, pk=share_id)
        share.delete()
        messages.add_message(
            request=request,
            level=messages.INFO,
            message='Le partage vient d\'être supprimé.',
        )
        return HttpResponseRedirect(reverse('core:shares', args=[share.server.pk]))

apps/core/views/ServerShareEditView.py
from core.decorators import CheckServerAuthorization
from core.forms import ServerShareEditForm
from core.models import Server, ServerShare
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('administrators'), name='dispatch')
class ServerShareEditView(View):
    """This is the share edit view."""

    def get(self, request, id: int, share_id: int):
        share = get_object_or_404(ServerShare, pk=share_id)
        form = ServerShareEditForm(
            data=request.POST or None,
            instance=share,
        )
        context = {
            'server': share.server,
            'share': share,
            'user_share': share.user,
            'form': form,
        }
        return render(request, 'core/settings/share_edit.html', context)

    def post(self, request, id: int, share_id: int):
        share = get_object_or_404(ServerShare, pk=share_id)
        form = ServerShareEditForm(
            data=request.POST,
            instance=share,
        )
        if form.is_valid():
            form.save()
            messages.add_message(
                request=request,
                level=messages.INFO,
                message='Le partage a bien été modifié.',
            )
            return HttpResponseRedirect(reverse('core:shares', args=[id]))
        else:
            messages.add_message(
                request=request,
                level=messages.ERROR,
                message='Le formulaire est incorrect.',
            )
        return self.get(request, id, share_id)

apps/core/views/ServerSharesView.py
from core.forms import ServerShareForm
from core.models import Server, ServerShare
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import (HttpResponseRedirect, get_object_or_404, render,
                              reverse)
from django.utils.decorators import method_decorator
from django.views import View

from core.decorators import CheckServerAuthorization


@method_decorator(login_required, name='dispatch')
@method_decorator(CheckServerAuthorization('administrators'), name='dispatch')
class ServerSharesView(View):
    """This is the share view."""

    def get(self, request, id):
        server = get_object_or_404(Server, pk=id)
        form = ServerShareForm(
            data=request.POST or None,
        )
        context = {
            'server': server,
            'form': form,
        }
        return render(request, 'core/settings/shares.html', context)

    def post(self, request, id):
        server = get_object_or_404(Server, pk=id)
        form = ServerShareForm(data=request.POST)
        if form.is_valid():
            user = User.objects.get(pk=request.POST['user'])
            try:
                share = ServerShare.objects.get(server=server, user=user)
            except ServerShare.DoesNotExist:
                share = None
            if share:
                form = ServerShareForm(
                    data=request.POST,
                    instance=share,
                )
                form.save()
                messages.add_message(
                    request=request,
                    level=messages.INFO,
                    message='Le partage existant a été modifié.',
                )
            else:
                share = form.save()
                share.server = server
                share.save()
                messages.add_message(
                    request=request,
                    level=messages.INFO,
                    message='Le partage a bien été créé.',
                )
        return self.get(request, id)

apps/core/templates/core/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block title %}Ajouter un serveur{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="pb-3">
        <a href="{% url 'core:manage' %}" class="btn btn-primary">← Retour</a>
    </div>
    <div class="mb-4">
        {% crispy form %}
    </div>
{% endblock content %}

apps/core/templates/core/index.html
{% extends 'base.html' %}

{% block title %}Serveurs Minecraft{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Bienvenue sur le gestionnaire de serveurs Minecraft</h1>
        <p class="lead">
            Vous pouvez créer des serveurs Minecraft lorsque vous en avez besoin juste ici !
        </p>
        <hr class="my-4">
        <p>
            Il n'y a qu'une seule règle : éteindre le serveur lorsque vous n'en avez plus besoin.
        </p>
        <a class="btn btn-primary btn-lg" href="{% url 'core:public-servers' %}" role="button">Parcourir les serveurs publics</a>
    </div>
{% endblock content %}

apps/core/templates/core/list.html
{% extends 'base.html' %}

{% block title %}Liste des serveurs plublics{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        {% if servers %}
            {% for server in servers %}
                {% include 'core/components/server_card.html' %}
            {% endfor %}
        {% else %}
            <p>Aucun serveur n'a été trouvé.</p>
        {% endif %}
    </div>
{% endblock content %}

apps/core/templates/core/manage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Gestion des serveurs{% endblock title %}

{% block head %}{% endblock head %}

{% block content %}
<div class="text-right pb-3">
    <a href="{% url 'core:add' %}" class="btn btn-primary">+ Ajouter un serveur</a>
</div>
<h1>Liste des serveurs</h1>
<h2>Mes serveurs</h2>
{% if servers %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
    {% for server in servers %}
    {% include 'core/components/server_card.html' %}
    {% endfor %}
</div>
{% else %}
<p>Vous ne possédez aucun serveur.</p>
{% endif %}
<h2>Serveurs partagés avec moi</h2>
{% if shared_servers %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
    {% for server in shared_servers %}
    {% include 'core/components/server_card.html' %}
    {% endfor %}
</div>
{% else %}
<p>Aucun serveur n'a été partagé avec vous.</p>
{% endif %}
{% endblock content %}

apps/core/templates/core/nav.html
{% load is_authorized %}
{% is_authorized 'manage' as manage_permission %}
{% is_authorized 'properties' as properties_permission %}
{% is_authorized 'administrators' as administrators_permission %}
{% is_authorized 'console' as console_permission %}
<div class="col col-12 col-md-3 mb-3">
    <ul class="list-group">
        <li class="list-group-item list-group-item-secondary">
            {% if server.image %}
            <img src="{{ server.image.url }}" alt="Image" style="height: 1.2em;" class="rounded mr-1">
            {% endif %}
            {{ server.name }}
        </li>
        {% if manage_permission %}
        <a href="{% url 'core:edit' server.pk %}" class="list-group-item{% if request.resolver_match.url_name == "edit" %} active{% endif %}">Paramètres globaux</a>
        {% endif %}
        {% if properties_permission %}
        <a href="{% url 'core:properties' server.pk %}" class="list-group-item{% if request.resolver_match.url_name == "properties" %} active{% endif %}">Propriétés</a>
        {% endif %}
        {% if administrators_permission %}
        <a href="{% url 'core:permissions' server.pk %}" class="list-group-item{% if request.resolver_match.url_name == "permissions" %} active{% endif %}">Permissions</a>
        <a href="{% url 'core:shares' server.pk %}" class="list-group-item{% if request.resolver_match.url_name == "shares" %} active{% endif %}">Partages</a>
        {% endif %}
    </ul>

    {% if manage_permission %}
    <ul class="list-group mt-3">
        {% if server.get_status %}
        <a href="{% url 'core:stop' server.pk %}" class="list-group-item list-group-item-danger">Eteindre</a>
        {% else %}
        <a href="{% url 'core:start' server.pk %}" class="list-group-item list-group-item-success">Démarrer</a>
        {% endif %}
    </ul>
    {% endif %}
</div>

apps/core/templates/core/settings.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% include 'core/nav.html' %}
        <div class="col">
            <h1>Gérer le serveur {{ server.name }}</h1>
            {% block body %}{% endblock body %}
        </div>
    </div>
{% endblock content %}