apps/account/urls.py
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name='profile'),
    path('user/', views.user, name='user'),
    path('password/', views.password, name='password'),
    path('connections/', views.connections, name='connections'),
    path('delete/', views.delete, name='delete'),
]

apps/core/urls.py
from django.urls import include, path

from core import views

app_name = "core"
urlpatterns = [
    path('', views.DefaultView.as_view(), name='index'),
    path('public-servers/', views.ServerListView.as_view(), name="public-servers"),
    path('manage/', views.ServerManageView.as_view(), name='manage'),
    path('server/add/', views.ServerCreateView.as_view(), name="add"),
    path('server/<int:id>/', include([
        path('share/<int:share_id>/', include([
            path('edit/', views.ServerShareEditView.as_view(), name="share-edit"),
            path('delete/', views.ServerShareDeleteView.as_view(), name="share-delete"),
        ])),
        path('edit/', views.ServerEditView.as_view(), name="edit"),
        path('properties/', views.ServerPropertiesView.as_view(), name="properties"),
        path('permissions/', views.ServerPermissionView.as_view(), name="permissions"),
        path('shares/', views.ServerSharesView.as_view(), name="shares"),
        path('delete/', views.ServerDeleteView.as_view(), name="delete"),
        path('start/', views.ServerStartView.as_view(), name="start"),
        path('stop/', views.ServerStopView.as_view(), name="stop"),
    ])),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include("social_django.urls", namespace="social")),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

apps/account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


def user_directory_path(instance, filename):
    """
    Indicates the location for saving a profile picture.

    Files will be uploaded to MEDIA_ROOT/avatar/user_<id>/<filename>
    """
    return 'avatar/user_{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    """Reprsents a user profile."""
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="related user",
    )
    biography = models.TextField(
        verbose_name="biography",
        help_text="300 characters maximum",
        max_length=300,
        blank=True,
        null=True,
    )
    website = models.URLField(
        verbose_name="web site",
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        verbose_name="profil picture",
        upload_to=user_directory_path,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.user.__str__()
    


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a profile and assign it to every new user."""
    if created:
        Profile.objects.create(user=instance)

apps/account/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "biography",
            "website",
            "avatar",
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

apps/account/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AdminPasswordChangeForm,
                                       PasswordChangeForm, UserCreationForm)
from django.shortcuts import HttpResponseRedirect, render, reverse
from django.template import Context, Template
from social_django.models import UserSocialAuth

from .forms import ProfileForm, UserForm


def index(request):
    return HttpResponseRedirect(reverse("account:profile"))


@login_required
def profile(request):
    """Profile view."""
    profile_form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=request.user.profile,
    )
    success = None

    if request.method == "POST" and profile_form.is_valid():
        profile_form.save()
        # To avoid the image link break
        profile_form = ProfileForm(instance=request.user.profile)
        success = True

    context = {
        "profile_form": profile_form,
        "success": success,
    }
    return render(request, "account/settings/profile.html", context)


@login_required
def user(request):
    """User view."""
    user_form = UserForm(
        data=request.POST or None,
        instance=request.user,
    )
    success = None

    if request.method == "POST" and user_form.is_valid():
        user_form.save()
        success = True

    context = {
        "user_form": user_form,
        "success": success,
    }
    return render(request, "account/settings/user.html", context)


@login_required
def password(request):
    """Password view."""
    if request.user.has_usable_password():
        form = PasswordChangeForm
    else:
        form = AdminPasswordChangeForm

    if request.method == "POST":
        password_form = form(request.user, request.POST)
        if password_form.is_valid():
            password_form.save()
            auth.update_session_auth_hash(request, password_form.user)
            return HttpResponseRedirect(
                reverse("account:password") + "?success=1"
            )
    else:
        password_form = form(request.user)

    context = {
        "password_form": password_form,
        "success": True if "success" in request.GET else None,
    }
    return render(request, "account/settings/password.html", context)


@login_required
def connections(request):
    """Connections view."""
    user = request.user
    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    services = []

    for provider in settings.ACCOUNTS_PROVIDERS:
        try:
            login = user.social_auth.get(provider=provider["provider"])
        except UserSocialAuth.DoesNotExist:
            login = None
        if login is not None:
            if provider["link"] is not None:
                template = Template(provider["link"])
                context = Context({"data": login.extra_data})
                link = template.render(context)
            else:
                link = None
            if provider["username"] is not None:
                template = Template(provider["username"])
                context = Context({"data": login.extra_data})
                username = template.render(context)
            else:
                username = None
        else:
            link = None
            username = None
        services.append({
            "provider": provider["provider"],
            "name": provider["name"],
            "login": login is not None,
            "link": link,
            "username": username,
        })

    context = {
        "services": services,
        "can_disconnect": can_disconnect
    }
    return render(request, "account/settings/connections.html", context)


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = auth.authenticate(username=username, password=raw_password)
            auth.login(request, user)
            return HttpResponseRedirect(reverse("login"))

    context = {
        "register_form": form,
    }
    return render(request, "account/register.html", context)


@login_required
def delete(request):
    """Delete user account."""
    request.user.delete()
    return HttpResponseRedirect("/")

apps/account/templates/base.html
<!doctype html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    {% block head %}{% endblock head %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container pt-4 pd-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

apps/account/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Minecraft-Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:public-servers' %}">Serveurs publics</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:manage' %}">Mes serveurs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:index' %}">Mon compte</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Se connecter</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>